"""add categories

Revision ID: af383b22b364
Revises: 96bfb7087d0b
Create Date: 2025-10-03 21:42:09.841544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # <-- add this under: import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'af383b22b364'
down_revision: Union[str, Sequence[str], None] = '96bfb7087d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_category_user_norm')
    )
    op.create_index(op.f('ix_category_normalized_name'), 'category', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)
    op.drop_index(op.f('idx_expense_user_cat_spent_at'), table_name='expense')
    op.drop_index(op.f('idx_expense_user_spent_at'), table_name='expense')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_expense_user_spent_at'), 'expense', ['user_id', 'spent_at'], unique=False)
    op.create_index(op.f('idx_expense_user_cat_spent_at'), 'expense', ['user_id', 'category', 'spent_at'], unique=False)
    op.drop_index(op.f('ix_category_user_id'), table_name='category')
    op.drop_index(op.f('ix_category_normalized_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
